<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="GameData\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Update="Replays\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
